// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module 'vue-multiselect' {
  export interface GlobalComponents {
    VueMultiselect: typeof import('vue-multiselect')['default']
  }
}