export enum Roles {
   ApoyoAdministrativo = "apoyo_administrativo",
   ApoyoJuridico = "apoyo_juridico",
   AsistenteAdministrativo = "asistente_administrativo",
   AuxiliarAdministrativoTecnico = "auxiliar_administrativo_tecnico",
   ContadorGeneral = "contador_general",
   CoordinadorPsicosocial = "coordinador_psicosocial",
   CoordinadorRegional = "coordinador_regional",
   CoordinadorZonaMaritima = "coordinador_zona_maritima",
   DirectorPrograma = "director_programa",
   DirectorTecnico = "director_tecnico",
   Mensajero = "mensajero",
   Metodologo = "metodologo",
   Monitor = "monitor",
   Periodista = "periodista",
   Psicologo = "psicologo",
   Root = "root",
   SubdirectorTecnico = "subdirector_tecnico",
   SuperRoot = "super.root",
   DirectorAdministrator = "director_administrator",
   CoordinadorMaritimo = "coordinador_maritimo",
}
